baseURL: "https://yay.qa/"
title: Yaroslav Yadryshnikov
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Yaroslav Yadryshnikov
  description: From Berdsk
  keywords: [Yaroslav Yadryshnikov, Ярослав Ядрышников]
  author: Yaroslav Yadryshnikov
  # author: ["Me", "You"] # multiple authors
  images: ["android-chrome-512x512.png"]
  DateFormat: "2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: Sup! 🤡

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Yaroslav Yadryshnikov
    subtitle: From Berdsk
    imageUrl: "avatar.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image

  socialIcons:
    - name: vk
      url: "https://vk.com/yay"
    - name: twitter
      url: "https://twitter.com/mryadro"
    - name: facebook
      url: "https://facebook.com/mryadro"
    - name: github
      url: "https://github.com/mryadro"
    - name: instagram
      url: "https://instagram.com/mryadro"
    - name: telegram
      url: "https://t.me/mryadro"
    - name: linkedin
      url: "https://linkedin.com/in/yay"
    - name: strava
      url: "https://www.strava.com/athletes/mryadro"
    - name: email
      url: "mailto:me@yay.qa"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page