baseURL = "https://yay.qa/"
title = "Yaroslav Yadryshnikov"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Yaroslav Yadryshnikov"
description = "From Berdsk"
keywords = [
    "Yaroslav Yadryshnikov",
    "Ярослав Ядрышников",
    "Iaroslav Iadryshnikov",
]
author = "Yaroslav Yadryshnikov"
images = ["android-chrome-512x512.png"]
DateFormat = "2 January, 2006"
defaultTheme = "auto"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.schema]
publisherType = "Person"

[params.label]
text = "Sup! 🤡"

[params.profileMode]
enabled = true
title = "Yaroslav Yadryshnikov"
subtitle = "From Berdsk"
imageUrl = "avatar.webp"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[menu.main]]
identifier = "wishlist"
name = "wishlist"
url = "posts/wishlist"
weight = 10

[[params.socialIcons]]
name = "vk"
url = "https://vk.com/yay"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/mryadro"

[[params.socialIcons]]
name = "mastodon"
url = "https://mstdn.social/@yay"

[[params.socialIcons]]
name = "facebook"
url = "https://facebook.com/mryadro"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mryadro"

[[params.socialIcons]]
name = "leetcode"
url = "https://leetcode.com/MrYadro"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/mryadro"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/mryadro"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/yay"

[[params.socialIcons]]
name = "strava"
url = "https://www.strava.com/athletes/mryadro"

[[params.socialIcons]]
name = "email"
url = "mailto:me@yay.qa"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true